name: macOS CI
on:
  push:
    paths:
      - '3.0/*'
  pull_request:
    paths:
      - '3.0/*'
jobs:
  build:
    runs-on: macos-latest
    env:
      CXXFLAGS: -std=${{ matrix.standard }} -Wno-error=deprecated-declarations
      INSPIRCD_DEBUG: 3
      INSPIRCD_VERBOSE: 1
    steps:
      - name: Checkout InspIRCd@insp3
        uses: actions/checkout@v2
        with:
          repository: 'inspircd/inspircd'
          ref: 'insp3'
          path: 'inspircd'
      - name: Checkout self
        uses: actions/checkout@v2
        with:
          path: 'contrib'
      - name: Symlink contrib modules
        run: |
          echo ::set-env name=INSPIRCD_TARGET::$(for f in contrib/3.0/*; do echo "$(basename $f .cpp) "; done)
          cd inspircd/src/modules
          ln -s ../../../contrib/3.0/* .
      - name: Install dependencies
        run: |
          brew update
          brew upgrade
          brew install pkg-config
      - name: Check for additional dependencies
        run: |
          cd inspircd
          echo ::set-env name=PACKAGES::$(for f in ../contrib/3.0/*; do ./tools/directive $f PackageInfo; done)
      - name: Install additional dependencies
        if: env.PACKAGES != ''
        run: brew install ${{ env.PACKAGES }}
      - name: Build the modules
        run: |
          cd inspircd
          ./configure --development --disable-auto-extras
          make --jobs $(($(sysctl -n hw.activecpu) + 1))
    strategy:
      fail-fast: false
      matrix:
        standard:
          - gnu++98
          - c++14
